global class DXF_ViewInterestWrapper {
	global string salutation;
    global string fName;
    global string lName;
    global string phone;
    global string email;
    global integer bedRoom;
    global integer minPrice;
    global integer maxPrice;
    global string interestType;
    global string location;
    global string matchPreference;
    global boolean emailAlertFlag;
    global string description;
    global date expectedMovingDate;
    global string lettingDuration;
}