global class DXF_AccountWrapper {
    global string SF_AccountID;
    global string lastName;
    global string firstName;
    global string Email;
    global string phone;
    global string Gender;
    global Date   Birthdate;
    global string Nationality;
    global string Address1;
    global string Address2;
    global string city;
    global string state;
    global string country;
    global string postalcode;
    global string adults;
    global string childrens;
    global string occupation;
    global string industry;
    global string incomeRange;
    global List<String> Interets;
    global List<String> vacation;
    global string Link;
    global string SocialName;

}