public class ReapitWebsitedatasync {
  @InvocableMethod
  public static void invokeAuraMethod(List<String> inputParams) {

    // Instantiate a new instance of the component that contains the Aura method.
    Druce_SecondaryPropertyAPI publishrecord = new Druce_SecondaryPropertyAPI();

    // Call the Aura method with the input parameters
    //publishrecord.calloutFromAura1(inputParams[0]);

  }

}